export type RootParamList = {
  Register: undefined;
  Privacy: undefined;
  Home: undefined;
  Login: undefined;
  ForgotPassword: undefined;
  DisplayName: undefined;
  GenderOrientation: undefined;
  DOB: undefined;
  SearchSettings: undefined;
  ProfileSettingsScreen: undefined;
  ViewMyProfileScreen: {
    userId?: string | number;
    targetUserId?: string | number;
    profileData?: any;
    image?: string | null;
    fallbackImage?: number;
  };
  OTPScreen: { sessionId?: string; phone?: string; mobile?: string; name?: string; password?: string; confirmPassword?: string };
  MatchScreen: { matchedUser: any };
  PrivacyPolicy: { type: 'privacy' | 'terms' };
  BottomTabs: undefined;
  AboutProfile: undefined;
  ConnectTelegram: undefined;
  ChatDetailScreen: { name: string; image: string | null };
  MoreDetails: undefined;
  SupportScreen: undefined;
  UploadImage: undefined;
  SelfieVerification: undefined;
};
